// name to key
//(?<=\{[\w\W]*?name: ".*),[\w\W]*?\}
//\{[\w\W]*?name: 
const clothesSlots = {
    "messenger bag": 3,
    "backpack": 5,
	"pyjama bottoms": 2,
	"waist apron": 1,
	"shorts": 2,
	"school shorts": 2,
	"school skirt": 2,
	"plant skirt": 2,
	"evening gown skirt": 1,
	"ballgown skirt": 1,
	"maid skirt": 2,
	"nun's habit skirt": 2,
	"tuxedo trousers": 2,
	"board shorts": 2,
	"breeches": 2,
	"long cut skirt": 1,
	"short cut skirt": 1,
	"cycle shorts": 2,
	"jeans": 4,
	"trousers": 4,
	"long skirt": 2,
	"miniskirt": 1,
	"long school skirt": 2,
	"short school skirt": 2,
	"school trousers": 4,
	"oversized sweater bottom": 1,
	"witch skirt": 1,
	"denim shorts": 2,
	"girl's oversized sweater bottom": 1,
	"christmas trousers": 2,
	"christmas skirt": 1,
	"monk's habit skirt": 1,
	"cowboy chaps": 4,
	"straightjacket bottom": 2,
	"khakis": 4,
	"gingham skirt": 1,
	"overall bottoms": 4,
	"chinos": 2,
	"gothic skirt": 1,
	"gothic trousers": 2,
	"waiter's trousers": 2,
	"lederhosen bottoms": 4,
	"karate trousers": 2,
	"sailor trousers": 2,
	"sailor shorts": 2,
	"football shorts": 2,
	"classic school shorts": 2,
	"classic school skirt": 2,
	"classic gothic skirt": 2,
	"scout shorts": 2,
	"soccer shorts": 2,
	"star pyjama shorts": 2,
	"moon pyjama bottoms": 2,
	"sweatpants": 1,
	"kilt": 3,
	"retro trousers": 2,
	"retro shorts": 2,
	"monster skirt": 2,
	"booty jorts": 1,
	"prison trousers": 2,
	"prison jumpsuit trousers": 2,
	"patient gown skirt": 2,
	"cow onesie bottoms": 2,
	"cow print chaps": 2,
	"baseball shorts": 2,
	"scarecrow skirt": 2,
	"waitress skirt": 2,
	"skimpy lolita skirt": 2,
	"slacks": 2,
	"pink nurse skirt": 2,
	"plastic nurse skirt": 2,
	"transparent nurse skirt": 2,
	"open shoulder sweater bottom": 1,
	"pencil skirt": 1,
	"ao dai trousers": 2,
	"traditional maid skirt": 2,
	"Victorian maid skirt": 2,
	"shrine maiden skirt": 2,
	"plaid school skirt": 2,
	"plaid school trousers": 2,
	"plaid school shorts": 2,
	"school pinafore": 2,
	"wide leg trousers": 2,
	"straight leg trousers": 2,
	"virgin killer skirt": 1,
	"leather skirt": 1,
	"dolphin shorts": 1,
	"school skirt": 2,
	"long school skirt": 2,
	"short school skirt": 2,
	"booty jorts": 1,
	"lolita skirt": 2,
	"gym shorts": 2,
	"shortalls": 2,
	"jingle-bell skirt": 2,
	"sleeveless jingle-bell skirt": 2,
	"school shirt": 1,
	"kimono": 1,
	"mini kimono": 1,
	"nun's habit": 1,
	"tuxedo jacket": 4,
	"turtleneck": 1,
	"vampire jacket": 4,
	"christmas shirt": 2,
	"monk's habit": 1,
	"checkered shirt": 2,
	"straightjacket": 2,
	"black leather jacket": 4,
	"brown leather jacket": 4,
	"cable knit turtleneck": 2,
	"turtleneck jumper": 1,
	"peacoat": 2,
	"gothic gown": 2,
	"gothic jacket": 4,
	"waiter's shirt": 1,
	"lederhosen": 1,
	"karate jacket": 4,
	"sailor shirt": 1,
	"padded football shirt": 1,
	"gym shirt": 1,
	"hunting coat": 4,
	"letterman jacket": 4,
	"racing silks": 1,
	"shadbelly coat": 3,
	"classic gothic gown": 1,
	"scout shirt": 1,
	"soccer shirt": 1,
	"puffer jacket": 4,
	"camo shirt": 1,
	"star pyjama shirt": 1,
	"moon pyjama shirt": 1,
	"hoodie": 1,
	"utility vest": 4,
	"utility vest with shirt": 4,
	"monster hoodie": 1,
	"patient gown": 2,
	"cropped hoodie": 1,
	"baseball shirt": 1,
	"scarecrow shirt": 1,
	"waitress uniform": 2,
	"single breasted jacket": 4,
	"double breasted jacket": 4,
	"winter jacket": 4,
	"classy vampire jacket": 4,
	"virgin killer": 1,
	"ao dai": 1,
	"school cardigan": 2,
	"school blouse": 2,
	"shrine maiden robes": 1,
	"polo shirt": 1,
	"band t-shirt": 1,
	"boxy t-shirt": 1,
	"gakuran": 2,
	"school sweater vest": 2,
}

Object.defineProperty(setup,"clothesSlots",{value:clothesSlots})