const positions = {
    PublicSquare:{
        name:"中央广场",
        desc:"中央广场四周都是餐厅和店铺，道路两旁摆满了桌子。这里算是城市的核心吧，每年5月举办猫之庆典时，中央广场就被装点得格外漂亮，游客人数也增加不少。",
        choice:["东广场|move_to:PublicSquareEast","西广场|move_to:PublicSquareWest","前往曼奇肯大道|travel:ManticanStreet","前往海滩|travel:Beach","前往日晷丘陵|travel:HillSundial","前往索马里大道|travel:SorumariStreet"]
    },
    PublicSquareEast:{
        name:"东广场",
        desc:"中央广场的东侧，这里有很多的空公寓，选择住在这里一定非常热闹。",
        choice:["走进「西伯利亚」烘焙坊|move_to:SiberiaBakery","离开|move_to:PublicSquare"]
    },
    PublicSquareWest:{
        name:"西广场",
        desc:"中央广场的西侧，有着很多的店铺，猫猫们懒洋洋的趴在店铺门口。",
        choice:["走进蛋糕店|move_to:CakeShop","走进剧院|move_to:Theater","走进咖啡屋|move_to:Cafe","走进可丽饼店|move_to:CrepeShop","离开|move_to:PublicSquare"]
    },
    SorumariStreet:{
        name:"索马里大道",
        desc:"从火车站到鱼市场附近，是交通要道。报社、市政府等建筑物都在火车站附近，很是热闹。",
        choice:["前往报社|move_to:Newspaper","前往市政府|move_to:CityHall","前往火车站|move_to:TrainStation","旅游大巴|move_to:TouristBus","前往中央广场|travel:PublicSquare","前往东方公园|travel:EastPark"]
    },
    ManticanStreet:{
        name:"曼奇肯大道",
        desc:"曼奇肯大道是主干道，左右两边都是经中央大桥出入城市的车辆。",
        choice:["前往中央大桥|travel:CityGate","前往中央广场|travel:PublicSquare","前往布利斯大道|travel:BricksStreet","前往哈瓦那大道|travel:HabanaStreet"]
    },
    HabanaStreet:{
        name:"哈瓦那大道",
        desc:"在哈瓦那大道举行的猫咪马戏团街头表演很受欢迎！自由猫们穿梭在队伍里更是一绝。",
        choice:["前往曼奇肯大道|travel:ManticanStreet","前往东方公园|travel:EastPark","前往利普尔港|travel:LeeplePort"]
    },
    EastPark:{
        name:"东方公园",
        desc:"城市东部的巨大的公园，白天参观天文台的人多，此时人声鼎沸；到了晚上就成了猫咪们的聚会地。",
        choice:["前往哈瓦那大道|travel:HabanaStreet"]
    },
    LeeplePort:{
        name:"利普尔港",
        desc:"靠近利普尔港，还得气息就越浓厚，渔船一艘艘出现在眼前，充满港口风情。",
        choice:["前往哈瓦那大道|travel:HabanaStreet","前往索马里大道|travel:SorumariStreet"]
    },
    Beach:{
        name:"海滩",
        desc:"从海滩上空可以俯瞰整个中央广场，还能看到远处的城堡，风景一绝。",
        choice:["前往中央广场|travel:PublicSquare"]
    },
    HillSundial:{
        name:"日晷丘陵",
        desc:"和平公园坐落于此，通往日晷丘陵的阶梯两侧有很多精品店，很是热闹。",
        choice:["前往杰克尼森林|travel:ZeconeForest","前往中央广场|travel:PublicSquare"]
    },
    ZeconeForest:{
        name:"杰克尼森林",
        desc:"位于诺贝尔克城堡南方的一大片森林，已经被指定为了国家公园。",
        choice:["前往日晷丘陵|travel:HillSundial"]
    },
    NyanbelcForest:{
        name:"诺贝尔克森林",
        desc:"由诺贝尔伯爵于14世纪兴建的城堡，至今仍保留着风貌，因此这座历史古城成了最著名的旅游经典。",
        choice:["前往布利斯大道|travel:BricksStreet"]
    },
    BricksStreet:{
        name:"布利斯大道",
        desc:"在坡度平缓的大道上，消防局、警察局坐落于此。",
        choice:["前往诺贝尔克森林|travel:NyanbelcForest","前往曼奇肯大道|travel:ManticanStreet"]
    },
    CityGate:{
        name:"中央大桥",
        desc:"大概是出城的唯一通道，海关和猫猫卫兵在这里站岗。",
        choice:["前往曼奇肯大道|travel:ManticanStreet"]
    },
    SiberiaBakery:{
        name:"「西伯利亚」烘焙坊",
        desc:"据说这家店第一个老板养了一只西伯利亚猫，于是索性就把店名起做「西伯利亚」了。|克罗华森正在楼梯上玩 酷儿正在柜台上睡觉",
        choice:["鱼面包(£3)|buy_item:FishBread;3","脚掌面包(£3)|buy_item:PawBread;3","猫形面包(£9)|buy_item:CatBread;9","脚印烧口袋三明治(£8.5)|buy_item:PawPocketSandwich;8.5","离开|move_to:PublicSquareEast"]
    },
    CakeShop:{
        name:"蛋糕店",
        desc:"中央广场的一家蛋糕店，售卖着各式各样的蛋糕。|梅普正在吃一块蛋糕 梅普正在努力上楼 梅普正在和顾客玩耍",
        choice:["猫形饼干(£11)|buy_item:CatBiscuit;11","鱼形饼干(£11)|buy_item:FishBiscuit;11","购买一块低糖减脂蛋糕(£10)|buy_item:FitnessCake;10","购买一角苹果派(£6.5)|buy_item:OneApplePie;6.5","购买整个苹果派(£39)|buy_item:ApplePie;39","离开|move_to:PublicSquareWest"]
    },
    Theater:{
        name:"剧院",
        desc:"结合了音乐厅、电影院、剧院等多功能设施，市民们经常来观赏演出。|杰克正在捉老鼠 杰克正在椅子上舔毛",
        choice:["观看电影(£20)|watch","欣赏古典音乐会|watch","离开|move_to:PublicSquareWest"]
    },
    Cafe:{
        name:"咖啡屋",
        desc:"位于中央广场的咖啡店，连接着广场和索马里大道。",
        choice:["猫猫咖啡(£5)|buy_item:PawCoffee;5","卡布奇诺(£6)|buy_item:Cappuccino;6","焦糖玛奇朵(£8)|buy_item:CaramelMacchiato;8","购买奶茶(£5)|buy_item:MilkTea;5","离开|move_to:PublicSquareWest"]
    },
    CrepeShop:{
        name:"可丽饼店",
        desc:"飘散着香甜的奶油香味，一只名叫“巧克力”的猫在椅子桑打盹。",
        choice:["草莓可丽饼(£10)|buy_item:CrepesStrawberry;10","香蕉可丽饼(£9)|buy_item:CrepesBanana;10","健康可丽饼(£9)|buy_item:CrepesFitness;9","奶油可丽饼(£5)|buy_item:CrepesCream;5","离开|move_to:PublicSquareWest"]
    },
    CityHall:{
        name:"市政府",
        desc:"城市的行政首脑，公务员们和猫们在大厅里穿梭。",
        choice:["离开|move_to:SorumariStreet"]
    },
    Newspaper:{
        name:"报社",
        desc:"整个城市的报社，在没有网络的年代，大概是唯一的媒体了吧。",
        choice:["买一份报(£2)|buy_item:CatNews;2","离开|move_to:SorumariStreet"]
    },
    TrainStation:{
        name:"火车站",
        desc:"非常热闹的车站，各种游客和本地居民出入往来。|卡米拉正在带小猫上厕所 卡米拉在长椅上休息",
        choice:["离开|move_to:SorumariStreet"],
    },
    TouristBus:{
        name:"旅游大巴",
        desc:"正前方的黄色建筑物是旅游局，满载着游客的巴士好像正要出发，前往哈瓦那大道。",
        choice:["前往哈瓦那大道|move_to:HabanaStreet","离开|move_to:SorumariStreet"],
    },
    PetalFlowerShop:{
        name:"花店「PETAL」",
        desc:"名叫Petal的花店，一进门便是浓郁的花香。铃兰、郁金香等对猫咪有毒地花朵被放到了高处。店员在给花们浇水。|弗洛拉在卖力地吃着猫草…… 弗洛拉在花丛中探头。",
        choice:["购买一朵红玫瑰(£2.5)|buy_item:RedRose;2.5","购买一把向日葵(£10)|buy_item:Sunflower;10","购买一朵郁金香(£4)|buy_item:Tulip;4","离开|move_to:SorumariStreet"],
    },
    LeeplePortStation:{
        name:"利普尔港车站",
        desc:"利普尔港车站内，白天总是繁忙熙攘，车流往来而去，而夜晚则一片寂静。",
        choice:["前往诺贝尔克森林|travel:NyanbelcForest","前往布利斯大道|travel:BricksStreet","前往哈瓦那大道|travel:HabanaStreet","前往曼奇肯大道|travel:ManticanStreet"],
    },
    SorumariNeighborhood:{
        name:"索马里住宅区",
        desc:"宁静的住宅区，坐落着众多小型宅院。",
        choice:["前往东方公园|travel:EastPark"]
    }
}
Object.defineProperty(window,"Positions",{value:positions})